config/routes.rb
Rails.application.routes.draw do

  mount Like::Engine => '/'
  mount Commontator::Engine => '/commontator'
  get 'home/index'
  post "/savesort" => 'home#savesort'
  get 'categories/get_category' => "categories#get_category"
  get 'categories/history', to: 'categories#history', as: :categories_history

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  resources :categories
  resources :albums, only: [:index, :new, :create, :show]
  resources :photographs, only: [:index, :new, :create, :show]

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photographs, :dependent => :destroy
  belongs_to :user
  acts_as_commontable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :new, :create]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(safe_album_params)

    if @album.save
      flash[:notice] = "You've uploaded a album!"
      redirect_to new_photograph_path
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  private
  def safe_album_params
    params.require(:album).permit(:name)
end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/index.html.erb
<br><h3><U>Gallery</u></h3>

<% @albums.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |photo| %>
      <div class="col-xs-2">
        <% @p = Photograph.where('album_id' => photo.id).first %>
        <%= link_to (image_tag @p.img.url, :width => '100%'), album_path(photo) %>
        <%=photo.name%>
      </div>
    <% end %>
  </div>
<% end %>

<div class="row" align="right">
  <%= link_to new_album_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-picture"></i>Create Album
  <%end%>

  <%= link_to new_photograph_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-picture"></i>Upload Photo
  <%end%>

  <%= link_to home_index_path, class: 'btn btn-primary' do %>
   <i class="glyphicon glyphicon-home"></i>Home
  <%end%>

</div>

app/views/albums/new.html.erb
<br><h3>Create Album</h3>

<%= form_for @album do |f| %>
<div class="row">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

<div class="row" align="right">

  <%= link_to albums_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-picture"></i>Gallery
  <%end%>

  <%= link_to home_index_path, class: 'btn btn-primary' do %>
  <i class="glyphicon glyphicon-home"></i>Home
  <%end%>
</div>

app/views/albums/show.html.erb
<br><h3><U><%= @album.name %> Album</u></h3>

<%= render :partial => 'photographs/index' %>

<% if Like::Like.liking?(current_user, @album) %>
  <%= link_to "<i class='glyphicon glyphicon-thumbs-down'></i> Unlike".html_safe, like_path_for(@album), method: :delete %>
<% else %>
  <%= link_to "<i class='glyphicon glyphicon-thumbs-up'></i> Like".html_safe, like_path_for(@album), method: :post %>
<% end %>
<br>

<%= commontator_thread(@album) %>