config/routes.rb
Rails.application.routes.draw do

  mount Like::Engine => '/'
  mount Commontator::Engine => '/commontator'
  get 'home/index'
  post "/savesort" => 'home#savesort'
  get 'categories/get_category' => "categories#get_category"
  get 'categories/history', to: 'categories#history', as: :categories_history

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  resources :categories
  resources :albums, only: [:index, :new, :create, :show]
  resources :photographs, only: [:index, :new, :create, :show]

end

app/models/photograph.rb
class Photograph < ActiveRecord::Base
  belongs_to :album
  mount_uploader :img, ImageUploader
  acts_as_commontable
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :show]

  def index
    @photographs = Photograph.all
  end

  def new
    @photograph = Photograph.new
  end

  def create
    @photograph = Photograph.new(safe_photograph_params)

    if @photograph.save
      flash[:notice] = "You've uploaded a photograph!"
      redirect_to albums_path
    else
      render :new
    end
  end

  def show
    @photograph = Photograph.find(params[:id])
  end

  private
  def safe_photograph_params
    params.require(:photograph).permit(:img,:album_id)
  end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/photographs/_index.html.erb
<div class="container">
  <ul class="row">
    <% @album.photographs.each do |photo| %>
        <li class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
          <%= image_tag photo.img.url, :width => '100%', :id => 'image_id' %>
            <% if Like::Like.liking?(current_user, photo) %>
              <%= link_to "<i class='glyphicon glyphicon-thumbs-down'></i> Unlike".html_safe, like_path_for(photo), :class => "like", method: :delete, data: { remote: "true" }  %>
            <% else %>
              <%= link_to "<i class='glyphicon glyphicon-thumbs-up'></i> Like".html_safe, like_path_for(photo), :class => "like", method: :post, data: { remote: "true" } %>
            <% end %>
           <%= Like::Like.with_likeable(photo).count %>
        </li>
    <%end%>
  </ul>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
     <!--  <div class="modal-footer">
        <a href=""></a>
      </div> -->
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="row" align="right">

<%= link_to new_photograph_path, class: 'btn btn-primary' do %>
  <i class="glyphicon glyphicon-picture"></i>Upload Photo
<%end%>

<%= link_to albums_path, class: 'btn btn-primary' do %>
  <i class="glyphicon glyphicon-picture"></i>Gallery
<%end%>

<%= link_to home_index_path, class: 'btn btn-primary' do %>
 <i class="glyphicon glyphicon-home"></i>Home
<%end%>

</div>

app/views/photographs/_show.html.erb
<!-- <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" style=" width:30%; height: 30%"> -->
  <!-- Indicators -->
  <!-- <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <!-- <div class="carousel-inner" role="listbox">

      <div class="item">
        <img src="" id="imagepreview" style="width: 100%; height: 100%;">
      </div>
  </div> -->

  <!-- Controls -->
<!--   <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> -->

<!-- <div id="myCarousel" class="carousel slide" data-ride="carousel">
 -->  <!-- Indicators -->
  <!-- <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol> -->

  <!-- Wrapper for slides -->
  <!-- <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="img_chania.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="img_chania2.jpg" alt="Chania">
    </div>

    <div class="item">
      <img src="img_flower.jpg" alt="Flower">
    </div>

    <div class="item">
      <img src="img_flower2.jpg" alt="Flower">
    </div>
  </div> -->

  <!-- Left and right controls -->
<!--   <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div> -->

<div id="photo_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">

      <div class="modal-body">
        <img src="" id="imagepreview" style="width: 100%; height: 100%;">
      </div>

      <div class="modal-footer">
       <span id="prev_photo">
          <%= link_to "<i class='glyphicon glyphicon-chevron-left'></i>".html_safe, "#", data: { remote: "true", toggle: 'modal', target: "#photo_modal" }, class: 'btn btn-primary' %>
        </span>
        <span>
          <%= link_to @p.next, class: 'btn btn-primary' do %>
          <i class="glyphicon glyphicon-chevron-right"></i><%end%>
        </span>
      </div>

    </div>
  </div>
</div>

app/views/photographs/new.html.erb
<br><h3><u>Upload a Photo</u></h3>

<h5>Pick a Picture</h5>

<%= form_for @photograph do |f| %>
<div class="row">
  <div class="field">
    <%= f.label :Photo %><br>
    <%= f.file_field :img %><br>
    <%= f.label :Album_Id %><br>
    <%= f.text_field :album_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>
<% end %>

<div class="row" align="right">
  <%= link_to home_index_path, class: 'btn btn-primary' do %>
  <i class="glyphicon glyphicon-home"></i>Home
  <%end%>
</div>

app/views/photographs/show.js.erb
// $("#photo_modal").html("<%= escape_javascript (render 'photographs/show')) %>");
// $("#photo_modal").modal("show")