config/routes.rb
Rails.application.routes.draw do

  mount Like::Engine => '/'
  mount Commontator::Engine => '/commontator'
  get 'home/index'
  post "/savesort" => 'home#savesort'
  get 'categories/get_category' => "categories#get_category"
  get 'categories/history', to: 'categories#history', as: :categories_history

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'home#index'

  resources :categories
  resources :albums, only: [:index, :new, :create, :show]
  resources :photographs, only: [:index, :new, :create, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
	acts_as_nested_set

	resourcify

  has_paper_trail

	belongs_to :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  load_and_authorize_resource

  def index
  	@categories=Category.all
  	@category=Category.new
  end

  def new
    @category=Category.new
  end

  def create
    @category =Category.create!(category_params)

    if @category.parent_id != nil
      @category.move_to_child_of(@category.parent_id)
    end

    if @category.save
      flash[:success] = 'Category was successfully created.'
    else
      flash[:danger] = 'There was a problem creating the Category.'
    end
    @category = Category.new
  end

  def show
    @category=Category.find(params[:id])
  end

  def get_category
    @category=Category.find(params[:id])

    respond_to do |format|
      format.html { @category }
      format.js { render json: @category.to_json }
    end
  end

  def edit
    @category=Category.find(params[:id])
  end

  def update
    @category=Category.find(params[:id])
      if @category.update_attributes(category_params)
        flash[:success] = 'Category was successfully updated.'
      else
        flash[:danger] = 'There was a problem updating the Category.'
      end
  end

  def destroy
    @category = Category.find(params[:id])
      if @category.destroy
        flash[:danger] = 'Category was successfully destroyed.'
      else
        flash[:danger] = 'There was a problem deleting the Category.'
      end
  end

  def history
    @versions = PaperTrail::Version.order('created_at DESC')
  end

  private
  	def category_params
    	params.require(:category).permit(:name,:parent_id)
 	 end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_edit.html.erb
<div class="modal-header">
  <h3 align="left"><u>Editing Category</u></h3>
</div>

<%= form_for(@category, remote: true, html: {role: :form, 'data-model' => 'category', :class => 'edit_category'}) do |f| %>
  <div class="row">
    <div class="form-group">
      <div class="col-md-2">
      </div>
      <div class="col-md-1">
        <%= f.label :Name %>
      </div>
      <div class="col-md-1">
        <%= f.text_field :name, :id => 'cat_name_field' %>
      </div>
      </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <div class="col-md-2">
      </div>
       <div class="col-md-1">
      </div>
      <div class="col-md-1">
        <div class="actions">

        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
        <%= f.submit 'Update Category', class: 'btn btn-success' %>
       <%= link_to "<i class='glyphicon glyphicon-remove'></i>Cancel".html_safe, "#", class: "btn btn-primary", data: {dismiss: "modal"} %>
    </div>
<% end %>

app/views/categories/_form.html.erb
<%= form_for(@category, remote: true, html: {role: :form, 'data-model' => 'category'}) do |f| %>
  <div class="row">
    <div class="form-group">
      <div class="col-md-2">
      </div>
      <div class="col-md-1">
        <%= f.label :Name %>
      </div>
      <div class="col-md-1">
        <%= f.text_field :name %>
      </div>
      <!--  <div class="col-md-8">
      </div> -->
      </div>
  </div>
  <br>
  <div class="row">
    <div class="form-group">
      <div class="col-md-2">
      </div>
       <div class="col-md-1">
        <%=f.hidden_field :parent_id, :id => "parent_field", :value => nil %>
      </div>
      <!-- <div class="col-md-1">
        <%#= f.text_field :parent_id %>
      </div> -->
    </div>
  </div>
  <br>
   <div class="modal-footer">
        <%= f.submit class: 'btn btn-success' %>
       <%= link_to "<i class='glyphicon glyphicon-remove'></i>Cancel".html_safe, "#", class: "btn btn-primary", data: {dismiss: "modal"} %>
      </div>
<% end %>

app/views/categories/_index.html.erb
<% @categories.each do |category| %>
  <div class="row">
    <div class="col-md-2">
      <%=category.name%>
    </div>
    <div class="col-md-2">
      <%=category.parent_id%>
    </div>
    <div class="col-md-2">
      <%=category.lft%>
    </div>
    <div class="col-md-2">
      <%=category.rgt%>
    </div>

    <div class="col-md-4">
      <%= link_to category, class: 'btn btn-info' do %>
        <i class="glyphicon glyphicon-eye-open"></i> Show <%end%>

      <%= link_to "#alert_modal", data: { toggle: 'modal', target: "#alert_modal" }, class: 'btn btn-primary' do %><i class='glyphicon glyphicon-pencil'></i>Edit<%end%>

      <% if cannot? :destroy , @category %>
          <%= link_to "#alert_modal",  data: { toggle: 'modal', target: "#alert_modal" },  class: 'btn btn-danger' do %><i class="glyphicon glyphicon-remove"></i> Destroy <%end%>
      <%else%>
         <%= link_to category, method: :delete, data: { confirm: "Are you sure want to delete?" },  class: 'btn btn-danger' do %><i class="glyphicon glyphicon-remove"></i> Destroy <%end%>
      <%end%>
    </div>
  </div>

  <div class="row">
    <hr style='background-color:rgb(255,0,0);border-width:0;color:#000000;height:0px;line-height:0;text-align:left;width:100%;'>
  </div>
<%end%>


<!-- Modal -->
<div id="alert_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">

       <div class="modal-body">
          <% if (cannot? :edit , @category) || (cannot? :destroy , @category) %>
              <span>Not allowed to do this action</span>
          <%end%>

          <% if can? :edit , @category %>
              <%#= render :action => "edit", modal: true %>
          <%end%>

      </div>

      <div class="modal-footer">
        <%= link_to "<i class='glyphicon glyphicon-remove'></i>Cancel".html_safe, "#", class: "btn btn-primary", data: {dismiss: "modal"} %>
      </div>
    </div>

  </div>
</div>

app/views/categories/_new.html.erb
<div class="modal-header">
  <h3 align="left"><u>New Category</u></h3>
</div>
    <%= render 'categories/form' %>
    <!-- <br> -->
   <!--  <div class="row">
      <%#= link_to categories_path, class: 'btn btn-primary' do%><i class="glyphicon glyphicon-arrow-left"></i> Back <%#end%>
    </div> -->

app/views/categories/create.js.erb
$("#category_form").modal("hide");
$("#category-sortable").html("<%= escape_javascript (render 'home/index') %>");

app/views/categories/destroy.js.erb
$("#category-sortable").html("<%= escape_javascript (render 'home/index') %>");

app/views/categories/edit.js.erb
$("#category_edit").html("<%= escape_javascript(render 'categories/edit') %>");
$("#category_edit").modal("show");

app/views/categories/history.html.erb
<div class="row">
  <h3><u>Histroy of Category</u></h3>
</div>

<div class="row" align="right">
  <%= link_to home_index_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-home"></i>Home
  <%end%>
</div><br>

<table class="table">
  <tr>
    <th>item_id</th>
    <th>item_type</th>
    <th>event</th>
    <th>whodunnit</th>
    <th>object</th>
  </tr>

   <% @versions.each do |version| %>
    <tr>
      <td><%=version.item_id%></td>
      <td><%=version.item_type%></td>
      <td><%=version.event%></td>
      <td><%=version.whodunnit%></td>
      <td><%=version.object%></td>
    </tr>
   <%end%>
</table>

app/views/categories/index.html.erb
<h3><u>Listing Categories</u></h3>

  <div id="content" class="row">

      <div class="row" align="right">
        <%= link_to home_index_path, class: 'btn btn-primary' do %>
          <i class="glyphicon glyphicon-home"></i>Home
        <%end%>
      </div>
      <div id="heading" class="row">
        <div class="col-md-2">
            <div class="row">
              <strong>Name</strong>
            </div>
        </div>
        <div class="col-md-2">
            <div class="row">
              <strong>Parent</strong>
            </div>
        </div>
        <div class="col-md-2">
          <div class="row">
              <strong>Left</strong>
            </div>
        </div>
      <div class="col-md-2">
          <div class="row">
              <strong>Right</strong>
            </div>
      </div>
        <div class="col-md-4">
        </div>
      </div>
      <div class="row">
         <hr style='background-color:rgb(255,0,0);border-width:0;color:#000000;height:2px;line-height:0;text-align:left;width:100%;'>
      </div>
      <div id="data" class="row">
          <%= render "index" %>
      </div>
      <div class="row">
        <hr style='background-color:rgb(255,0,0);border-width:0;color:#000000;height:2px;line-height:0;text-align:left;width:100%;'>
      </div>
  </div>

app/views/categories/new.js.erb
$("#category_form").html("<%= escape_javascript (render 'categories/form')) %>");
$("#category_form").modal("show")

app/views/categories/show.html.erb
<div class="row">
    <div class="col-md-10">
      <div class="row">
        <h1><u>Show Category</u></h1>
      </div>
      <br>
      <div class="row">
        <strong>Name :-</strong>
        <%= @category.name %>
      </div>
      <br>
      <div class="row">
        <strong>Parent :-</strong>
      <%= @category.parent_id %>
      </div>
      <br>
       <div class="row">
        <strong>Left :-</strong>
        <%= @category.lft %>
      </div>
      <br>
       <div class="row">
        <strong>Right :-</strong>
        <%= @category.rgt %>
      </div>
      <br>
        <div class="row ">
            <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
            <i class="glyphicon glyphicon-pencil"></i> Edit <%end%>
            <%= link_to categories_path, class: 'btn btn-primary' do%><i class="glyphicon glyphicon-arrow-left"></i> Back <%end%>
        </div>
    </div>
    <div class="col-md-2">
    </div>
</div>

app/views/categories/update.js.erb
$("#category_edit").modal("hide");
$("#category-sortable").html("<%= escape_javascript (render 'home/index') %>");